### ISSUE TITLE
Getting exception reading XML?

### ISSUE THREAD

**Issue by chrisaaaaa** [jenkinsci/perfpublisher-plugin#13]
I am trying to use this plugin in Jenkins, I have written code in my build to write an XML file that I think is right. I cannot find xml-generate.jar for an example so am using the details on the plugin wiki page.

The plugin gives an exception parsing a float for state (line 423), I have a normal 2 digit fp number as an attribute so cannot see what is wrong.

Is there an example file, XSD etc?

Is anyone up to speed with this whoo could parse this?
`
<report name="Code memory" categ="Memory">	
<test name="totalSizeInBytes" executed="yes">	
<description>Size of program code plus largest overlay</description>	
<result>	
<success passed="yes" state="1.12" isRelevant="true"/>	
<performance unit="Bytes" mesure="129602" isRelevant="true"/>	
<metrics>	
<progspacefree unit="Bytes" mesure="1470" isRelevant="true"/>	
</metrics>	
</result>	
</test>		
<test name="sharedSize" executed="yes">	
<description>Size of shared data memory</description>	
<result>	
<success passed="yes" state="1.66" isRelevant="true"/>	
<performance unit="Bytes" mesure="15104" isRelevant="true"/>	
<metrics>	
<sharspacefree unit="Bytes" mesure="256" isRelevant="true"/>	
</metrics>	
</result>	
</test>							
<test name="dataMemUsed" executed="yes">	
<description>Size of data memory</description>	
<result>	
<success passed="yes" state="2.49" isRelevant="true"/>	
<performance unit="Bytes" mesure="62896" isRelevant="true"/>	
<metrics>	
<datamemfree unit="Bytes" mesure="1612" isRelevant="true"/>	
</metrics>	
</result>	
</test>							
<test name="totalCodeResident" executed="yes">	
<description>Size of program code in data memory</description>	
<result>	
<success passed="yes" isRelevant="true"/>	
<performance unit="Bytes" mesure="150254" isRelevant="true"/>	
<metrics>	
<totalFreeBytes unit="Bytes" mesure="3338" isRelevant="true"/>	
</metrics>	
</result>	
</test>							
</report>
`
TIA

Chris

**Comment by eschava** [comment]
You should have "start" element like in the report below:

<?xml version="1.0"?>
<report name="GeneratedReport-0" categ="GeneratedReport" >
	<start>
		<date format="YYYYMMDD" val="20170627" />
		<time format="HHMMSS" val="151824" />
	</start>
	<test name="test1" executed="yes" >
		<result>
			<success passed="yes" state="100" />
			<executiontime unit="s" mesure="11.277" isRelevant="false" />
			<metrics>
				<RestartProcesses unit="s" mesure="0.0" isRelevant="false" />
				<Sleep unit="s" mesure="0.0" isRelevant="false" />
			</metrics>
		</result>
	</test>
	<test name="test2" executed="yes" >
		<result>
			<success passed="yes" state="100" />
			<executiontime unit="s" mesure="8.595" isRelevant="false" />
			<metrics>
				<RestartProcesses unit="s" mesure="0.0" isRelevant="false" />
				<Sleep unit="s" mesure="0.0" isRelevant="false" />
			</metrics>
		</result>
	</test>
	<test name="test3" executed="yes" >
		<result>
			<success passed="yes" state="100" />
			<executiontime unit="s" mesure="9.049" isRelevant="false" />
			<metrics>
				<RestartProcesses unit="s" mesure="0.0" isRelevant="false" />
				<Sleep unit="s" mesure="0.0" isRelevant="false" />
			</metrics>
		</result>
	</test>
	<test name="Total" executed="yes" >
		<result>
			<success passed="yes" state="100" />
			<executiontime unit="s" mesure="9.049" isRelevant="true" />
			<metrics>
				<RestartProcesses unit="s" mesure="0.0" isRelevant="true" />
				<Sleep unit="s" mesure="0.0" isRelevant="true" />
			</metrics>
		</result>
	</test>
</report>

**Comment by eschava** [comment]
You should have "start" element like in the report below:

```
<?xml version="1.0"?>
<report name="GeneratedReport-0" categ="GeneratedReport" >
	<start>
		<date format="YYYYMMDD" val="20170627" />
		<time format="HHMMSS" val="151824" />
	</start>
	<test name="test1" executed="yes" >
		<result>
			<success passed="yes" state="100" />
			<executiontime unit="s" mesure="11.277" isRelevant="false" />
			<metrics>
				<RestartProcesses unit="s" mesure="0.0" isRelevant="false" />
				<Sleep unit="s" mesure="0.0" isRelevant="false" />
			</metrics>
		</result>
	</test>
	<test name="test2" executed="yes" >
		<result>
			<success passed="yes" state="100" />
			<executiontime unit="s" mesure="8.595" isRelevant="false" />
			<metrics>
				<RestartProcesses unit="s" mesure="0.0" isRelevant="false" />
				<Sleep unit="s" mesure="0.0" isRelevant="false" />
			</metrics>
		</result>
	</test>
	<test name="test3" executed="yes" >
		<result>
			<success passed="yes" state="100" />
			<executiontime unit="s" mesure="9.049" isRelevant="false" />
			<metrics>
				<RestartProcesses unit="s" mesure="0.0" isRelevant="false" />
				<Sleep unit="s" mesure="0.0" isRelevant="false" />
			</metrics>
		</result>
	</test>
	<test name="Total" executed="yes" >
		<result>
			<success passed="yes" state="100" />
			<executiontime unit="s" mesure="9.049" isRelevant="true" />
			<metrics>
				<RestartProcesses unit="s" mesure="0.0" isRelevant="true" />
				<Sleep unit="s" mesure="0.0" isRelevant="true" />
			</metrics>
		</result>
	</test>
</report>

```

**Comment by eschava** [comment]
Right, "state" is parsed using Float.parseFloat method so format depends on the locale settings

**Comment by chrisaaaaa** [comment]
Thanks the example should really help, I will try it out.

**Comment by chrisaaaaa** [comment]
Thanks that fixed it.

And for anyone googling in the future
example template perfpublisher jenkins plugin xml file format
