### ISSUE TITLE
Cannot seem to refresh reports

### ISSUE THREAD

**Issue by chrisaaaaa** [jenkinsci/perfpublisher-plugin#14]
Not so much an issue as a feature request, but probably there is a workaround.

Promise - not trying to edit results :)

In my system I have some python that parses some very extensive logs to produce a perfpublisher compatible XML file. As I improve the python I get more and more metrics.

What I would like to do is replace the xml file with a new file with more metrics and have the GlobalTestReport pick up the results, this would mean I can back fill more data on the test runs, some of which take a week to run.

I have tried reload from disk and restarts of Jenkins, no effect, perfpublisher must have read the xml file and  cached something somewhere, but where? Maybe I could just delete it?

TIA

Chris

**Comment by eschava** [comment]
All results are duplicated in build.xml file inside build folder
There are results for single tests + best/worst/average results

**Comment by chrisaaaaa** [comment]
@eschava 

Thanks, that helps a bit, I can see a lot (about 75k lines) that looks like the same data presented slightly differently.

Is there a way I can get it to perform the input and transformation again?

Chris

**Comment by eschava** [comment]
Sorry, I'm not sure there is some way to do this.
