### ISSUE TITLE
Some html displayed as plain text.

### ISSUE THREAD

**Issue by Bazyli-Kot** [jenkinsci/perfpublisher-plugin#19]
With older version of Jenkins plugin worked fine. Since upgrade some of the report components are displayed as plaintext instead of html.

![image](https://user-images.githubusercontent.com/45999661/50225010-9f5f0a00-039f-11e9-8f25-901dc8345e79.png)

![image](https://user-images.githubusercontent.com/45999661/50225030-b140ad00-039f-11e9-9b1e-3628ee64e2d7.png)

![image](https://user-images.githubusercontent.com/45999661/50225035-b56cca80-039f-11e9-9178-381f7afc05e7.png)

Thanks,
Bazyli

**Comment by eschava** [comment]
Please check new release

**Comment by eschava** [comment]
Could you please try non-released version built by me?
hpi file is present inside zip

[perfpublisher.zip](https://github.com/jenkinsci/perfpublisher-plugin/files/2714842/perfpublisher.zip)
