### ISSUE TITLE
Possibility of hiding chosen graphs in the report

### ISSUE THREAD

**Issue by kisieel** [jenkinsci/perfpublisher-plugin#3]
It is impossible to show only selected statistics in the report, which would be usefull in many applications, like for example embedded system regression test result publishing - in such cases complie time and performance are not tracked. 
untracked parameters should also be removed from all tables in build detailed report.

**Comment by eschava** [comment]
Hi

You can check my fork of perfpublisher hiding charts without data
https://github.com/eschava/perfpublisher-plugin/releases/tag/perfpublisher-8.01

**Comment by langers2k** [comment]
Merged.
