### ISSUE TITLE
Additional attributes for custom metrics are ignored

### ISSUE THREAD

**Issue by eschava** [jenkinsci/perfpublisher-plugin#5]
Documentation for plugin at https://wiki.jenkins-ci.org/display/JENKINS/PerfPublisher+Plugin states that
metrics have next format
<metrics>
        <{CUSTOM_METRIC_ID} unit="{UNIT}" mesure="{MEASURE}" isRelevant="{IS_RELEVANT}" />
      </metrics>

but code parsing XML ignores all attributes except "measure".
Proof:

```
			} else if (this.metrics_name.contains(qName) && f_report && f_test && f_result && f_metrics) {
				//We have discovered a metric
				//It should have attribute value
				if (attributes.getValue("mesure")!=null) {
					double value = Double.parseDouble(attributes.getValue("mesure"));
					this.metrics.put(qName, value);
					buffer = new StringBuffer();
				}
			} 
```

as a result average value is wrong because isRelevant attribute is ignored

**Comment by langers2k** [comment]
Make a PR and I'll get it merged. Do you want to become the maintainer as this is something I'm not too interested in currently.

**Comment by hackrid** [comment]
this is really sad since the graph is labeled "Gflops" by default

**Comment by eschava** [comment]
Gflops is a unit for Performace metric only
All custom metrics have "unit" unit on charts
But I've also have the change (not added to PR yet) to have correct unit for custom metric charts

**Comment by hackrid** [comment]
how do I generate a entry for a custom metric "unit" ?
